INSERT INTO book (author, name) VALUES
  (E'Mr. Westley Davis', E'Rwanda'),
  (E'Amaya Willms', E'Jordan'),
  (E'Kianna Will', E'Guadeloupe'),
  (E'Gaetano Glover', E'Iceland'),
  (E'Lucile Keeling', E'Antigua and Barbuda'),
  (E'Ayla Stokes', E'Zambia'),
  (E'Johan Stamm', E'United Kingdom'),
  (E'Jerrod Leffler', E'Tajikistan'),
  (E'Jamar Heaney', E'Burkina Faso'),
  (E'Dagmar Moen DVM', E'Sri Lanka'),
  (E'Dr. Derek Fritsch', E'Bahrain'),
  (E'Scarlett Champlin', E'Christmas Island'),
  (E'Jailyn Herzog', E'Papua New Guinea'),
  (E'Ernesto Kirlin', E'Canada'),
  (E'Stephan Waelchi', E'Japan'),
  (E'Mariane Leannon', E'Guernsey'),
  (E'Zoey Howell', E'South Georgia and the South Sandwich Islands'),
  (E'Violette Smitham', E'Madagascar'),
  (E'Glenda Kerluke', E'Lesotho'),
  (E'Ms. Kailyn Botsford', E'Réunion'),
  (E'Althea Bins', E'Solomon Islands'),
  (E'Obie Grant', E'Lebanon'),
  (E'Buck Witting', E'Angola'),
  (E'Julian Kris', E'Saint Pierre and Miquelon'),
  (E'Trycia Stehr', E'Malawi'),
  (E'Rickie Daugherty', E'South Korea'),
  (E'Garnett Hilll', E'Pitcairn Islands'),
  (E'Hester Langworth', E'Turkey'),
  (E'Tony Haag', E'Aruba'),
  (E'Damon Fisher', E'Djibouti'),
  (E'Velma Windler', E'Mexico'),
  (E'George Welch', E'Saint Vincent and the Grenadines'),
  (E'Neoma Schroeder', E'Saint Kitts and Nevis'),
  (E'Sincere Considine', E'Faroe Islands'),
  (E'Destinee Waelchi', E'São Tomé and Príncipe'),
  (E'Trycia DuBuque', E'Bangladesh'),
  (E'Tristian Bahringer', E'Guyana');
